server:
  servlet:
    contextPath: /automation/api/v1
  port: 8082

spring:
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5434/automation
    username: app
    password: app
  #datasource:
  #  url: jdbc:h2:file:~/test4
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver
  batch:
    job:
      enabled: true
    initialize-schema: always

automation:
  enabled: true
  job-start-time: 0 */1 * * * ?